import { PALETTES, PlateConfig } from '../utils/plateGenerator';

export const PLATE_CATALOG: PlateConfig[] = [
  { plate_id: 'p01', number: '12', type: 'demonstration', colors: PALETTES.NORMAL, difficulty: 1 },
  { plate_id: 'p02', number: '8', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p03', number: '6', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p04', number: '29', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p05', number: '57', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p06', number: '5', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p07', number: '3', type: 'diagnostic', colors: PALETTES.CVD_CONFUSION_1, difficulty: 5 },
  { plate_id: 'p08', number: '15', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p09', number: '74', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p10', number: '45', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p11', number: '16', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p12', number: '2', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p13', number: '97', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p14', number: '35', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p15', number: '96', type: 'diagnostic', colors: PALETTES.CVD_CONFUSION_1, difficulty: 5 },
  { plate_id: 'p16', number: '42', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p17', number: '10', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p18', number: '7', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p19', number: '13', type: 'diagnostic', colors: PALETTES.CVD_CONFUSION_1, difficulty: 5 },
  { plate_id: 'p20', number: '26', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p21', number: '18', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p22', number: '9', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p23', number: '22', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p24', number: '4', type: 'diagnostic', colors: PALETTES.CVD_CONFUSION_1, difficulty: 5 },
  { plate_id: 'p25', number: '81', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p26', number: '63', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
  { plate_id: 'p27', number: '51', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 3 },
  { plate_id: 'p28', number: '38', type: 'diagnostic', colors: PALETTES.CVD_CONFUSION_1, difficulty: 5 },
  { plate_id: 'p29', number: '25', type: 'diagnostic', colors: PALETTES.NORMAL, difficulty: 2 },
  { plate_id: 'p30', number: '77', type: 'diagnostic', colors: PALETTES.REVERSED, difficulty: 4 },
];
